#if !defined(AFX_REPOSPROPERTIES_H__1155CC4D_BC16_4137_9560_59F8EF90E784__INCLUDED_)
#define AFX_REPOSPROPERTIES_H__1155CC4D_BC16_4137_9560_59F8EF90E784__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CReposProperty;

/////////////////////////////////////////////////////////////////////////////
// CReposProperties wrapper class

class CReposProperties : public COleDispatchDriver
{
public:
	CReposProperties() {}		// Calls COleDispatchDriver default constructor
	CReposProperties(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CReposProperties(const CReposProperties& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CReposProperty GetItem(const VARIANT& sItem);
	VARIANT GetType();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_REPOSPROPERTIES_H__1155CC4D_BC16_4137_9560_59F8EF90E784__INCLUDED_)
