#if !defined(AFX_REPOSITORYTRANSACTION_H__16CE75ED_EEE9_43A1_B2BC_C819488FB811__INCLUDED_)
#define AFX_REPOSITORYTRANSACTION_H__16CE75ED_EEE9_43A1_B2BC_C819488FB811__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRepositoryTransaction wrapper class

class CRepositoryTransaction : public COleDispatchDriver
{
public:
	CRepositoryTransaction() {}		// Calls COleDispatchDriver default constructor
	CRepositoryTransaction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRepositoryTransaction(const CRepositoryTransaction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Begin();
	void Commit();
	void Abort();
	long GetStatus();
	VARIANT GetOption(long iOption);
	void SetOption(long iOption, const VARIANT& sValue);
	void Flush();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_REPOSITORYTRANSACTION_H__16CE75ED_EEE9_43A1_B2BC_C819488FB811__INCLUDED_)
