//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickUsbDiagCs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FpgaFilePath {
            get {
                return ((string)(this["FpgaFilePath"]));
            }
            set {
                this["FpgaFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00")]
        public string CommandReadAddress {
            get {
                return ((string)(this["CommandReadAddress"]));
            }
            set {
                this["CommandReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string CommandReadBytes {
            get {
                return ((string)(this["CommandReadBytes"]));
            }
            set {
                this["CommandReadBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00")]
        public string CommandWriteAddress {
            get {
                return ((string)(this["CommandWriteAddress"]));
            }
            set {
                this["CommandWriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string CommandWriteBytes {
            get {
                return ((string)(this["CommandWriteBytes"]));
            }
            set {
                this["CommandWriteBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07")]
        public string CommandWriteData {
            get {
                return ((string)(this["CommandWriteData"]));
            }
            set {
                this["CommandWriteData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65536")]
        public string DataReadBytes {
            get {
                return ((string)(this["DataReadBytes"]));
            }
            set {
                this["DataReadBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data_read.bin")]
        public string DataReadFilePath {
            get {
                return ((string)(this["DataReadFilePath"]));
            }
            set {
                this["DataReadFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x0000")]
        public string DataReadStartAddress {
            get {
                return ((string)(this["DataReadStartAddress"]));
            }
            set {
                this["DataReadStartAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65536")]
        public string DataWriteBytes {
            get {
                return ((string)(this["DataWriteBytes"]));
            }
            set {
                this["DataWriteBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataWriteEntireFile {
            get {
                return ((bool)(this["DataWriteEntireFile"]));
            }
            set {
                this["DataWriteEntireFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data_write.bin")]
        public string DataWriteFilePath {
            get {
                return ((string)(this["DataWriteFilePath"]));
            }
            set {
                this["DataWriteFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x0000")]
        public string DataWriteStartAddress {
            get {
                return ((string)(this["DataWriteStartAddress"]));
            }
            set {
                this["DataWriteStartAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00 0x01")]
        public string RS232WriteData {
            get {
                return ((string)(this["RS232WriteData"]));
            }
            set {
                this["RS232WriteData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string SpiReadBytes {
            get {
                return ((string)(this["SpiReadBytes"]));
            }
            set {
                this["SpiReadBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00 0x01")]
        public string SpiWriteData {
            get {
                return ((string)(this["SpiWriteData"]));
            }
            set {
                this["SpiWriteData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x60")]
        public string I2cReadAddress {
            get {
                return ((string)(this["I2cReadAddress"]));
            }
            set {
                this["I2cReadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string I2cReadBytes {
            get {
                return ((string)(this["I2cReadBytes"]));
            }
            set {
                this["I2cReadBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x60")]
        public string I2cWriteAddress {
            get {
                return ((string)(this["I2cWriteAddress"]));
            }
            set {
                this["I2cWriteAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x00 0x01")]
        public string I2cWriteData {
            get {
                return ((string)(this["I2cWriteData"]));
            }
            set {
                this["I2cWriteData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedTabIndex {
            get {
                return ((int)(this["SelectedTabIndex"]));
            }
            set {
                this["SelectedTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EpcsFilePath {
            get {
                return ((string)(this["EpcsFilePath"]));
            }
            set {
                this["EpcsFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public decimal RepeatInterval {
            get {
                return ((decimal)(this["RepeatInterval"]));
            }
            set {
                this["RepeatInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("streaming_read.bin")]
        public string DataStreamReadFilePath {
            get {
                return ((string)(this["DataStreamReadFilePath"]));
            }
            set {
                this["DataStreamReadFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("streaming_write.bin")]
        public string DataStreamWriteFilePath {
            get {
                return ((string)(this["DataStreamWriteFilePath"]));
            }
            set {
                this["DataStreamWriteFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65536")]
        public string StreamBytes {
            get {
                return ((string)(this["StreamBytes"]));
            }
            set {
                this["StreamBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string StreamNumBuffers {
            get {
                return ((string)(this["StreamNumBuffers"]));
            }
            set {
                this["StreamNumBuffers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string StreamNumThreads {
            get {
                return ((string)(this["StreamNumThreads"]));
            }
            set {
                this["StreamNumThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string StreamThreadConcurrency {
            get {
                return ((string)(this["StreamThreadConcurrency"]));
            }
            set {
                this["StreamThreadConcurrency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1048576")]
        public string StreamMaxBytes {
            get {
                return ((string)(this["StreamMaxBytes"]));
            }
            set {
                this["StreamMaxBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16777216")]
        public string StreamReadMemFileSize {
            get {
                return ((string)(this["StreamReadMemFileSize"]));
            }
            set {
                this["StreamReadMemFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16777216")]
        public string StreamWriteMemFileSize {
            get {
                return ((string)(this["StreamWriteMemFileSize"]));
            }
            set {
                this["StreamWriteMemFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DataOutOfOrder {
            get {
                return ((bool)(this["DataOutOfOrder"]));
            }
            set {
                this["DataOutOfOrder"] = value;
            }
        }
    }
}
